package com.airfrance.admin.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OffreAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOffreAllPropertiesEquals(Offre expected, Offre actual) {
        assertOffreAutoGeneratedPropertiesEquals(expected, actual);
        assertOffreAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOffreAllUpdatablePropertiesEquals(Offre expected, Offre actual) {
        assertOffreUpdatableFieldsEquals(expected, actual);
        assertOffreUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOffreAutoGeneratedPropertiesEquals(Offre expected, Offre actual) {
        assertThat(actual)
            .as("Verify Offre auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOffreUpdatableFieldsEquals(Offre expected, Offre actual) {
        assertThat(actual)
            .as("Verify Offre relevant properties")
            .satisfies(a -> assertThat(a.getPriorite()).as("check priorite").isEqualTo(expected.getPriorite()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOffreUpdatableRelationshipsEquals(Offre expected, Offre actual) {
        assertThat(actual)
            .as("Verify Offre relationships")
            .satisfies(a -> assertThat(a.getVol()).as("check vol").isEqualTo(expected.getVol()));
    }
}
