package com.airfrance.admin.domain;

import static com.airfrance.admin.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class VolAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVolAllPropertiesEquals(Vol expected, Vol actual) {
        assertVolAutoGeneratedPropertiesEquals(expected, actual);
        assertVolAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVolAllUpdatablePropertiesEquals(Vol expected, Vol actual) {
        assertVolUpdatableFieldsEquals(expected, actual);
        assertVolUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVolAutoGeneratedPropertiesEquals(Vol expected, Vol actual) {
        assertThat(actual)
            .as("Verify Vol auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVolUpdatableFieldsEquals(Vol expected, Vol actual) {
        assertThat(actual)
            .as("Verify Vol relevant properties")
            .satisfies(a -> assertThat(a.getOrigin()).as("check origin").isEqualTo(expected.getOrigin()))
            .satisfies(a -> assertThat(a.getDestination()).as("check destination").isEqualTo(expected.getDestination()))
            .satisfies(a -> assertThat(a.getAllerRetour()).as("check allerRetour").isEqualTo(expected.getAllerRetour()))
            .satisfies(a -> assertThat(a.getPrix()).as("check prix").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrix()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVolUpdatableRelationshipsEquals(Vol expected, Vol actual) {
        // empty method
    }
}
